title: <p align="center"> Shrayak Tomar </p>
logo: /assets/img/2.jpg

description:
  <p align="center">
  <a href="https://github.com/shrayak tomar">GitHub</a>
  
  <br>   
  I work on different projects of ML & AI and Cybersecurity while pursuing masters in Ml and AI
  Here are my all the collection of the projects some completed some are in progress
  i have been also trying to contribute in open source projects 
  <br>
  </p>



theme: jekyll-theme-minimal
